### ISSUE TITLE
Not compatible with aiorpcX 0.19+

### ISSUE THREAD

**Issue by sidamos** [spesmilo/electrumx#160]
It works fine with 0.18.5.

With 0.19.1, it says it needs 0.18.5+.

With 0.22.1, it gets an argument error:
TypeError: spawn() got an unexpected keyword argument 'report_crash'

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc
